
import java.io.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nikos
 */
public class FourthInputForm extends javax.swing.JFrame {

    /**
     * Creates new form FourthInputForm
     */
    public FourthInputForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ΥΠΟΛΟΓΙΣΜΟΣ ΚΟΙΝΟΧΡΗΣΤΩΝ");

        jButton1.setText("ΔΗΜΙΟΥΡΓΙΑ ΑΠΟΔΕΙΞΕΩΝ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Μήνας και έτος εξόδων:");

        TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextField1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] output2Array = new String[65535];

        int counter2 = 0;
        try {
            BufferedReader br = new BufferedReader(new FileReader("output2.txt"));
            String lineContents = br.readLine();

            while (lineContents != null) {
                output2Array[counter2] = lineContents;
                lineContents = br.readLine();
                counter2++;
            }
            br.close();
        } catch (IOException e) {
            e.getMessage();
        }

        String[] output3Array = new String[65535];

        int counter3 = 0;
        try {
            BufferedReader br = new BufferedReader(new FileReader("output3.txt"));
            String lineContents = br.readLine();

            while (lineContents != null) {
                output3Array[counter3] = lineContents;
                lineContents = br.readLine();
                counter3++;
            }
            br.close();
        } catch (IOException e) {
            e.getMessage();
        }

        int aCosts = -1;
        int bCosts = -1;
        int cCosts = -1;
        int dCosts = -1;
        for (int i = 0; i < counter3; i++) {
            if ((output3Array[i].equals(this.getTitle())) && (output3Array[i + 1].equals(TextField1.getText()))) {
                aCosts = Integer.parseInt(output3Array[i + 2]);
                bCosts = Integer.parseInt(output3Array[i + 3]);
                cCosts = Integer.parseInt(output3Array[i + 4]);
                dCosts = Integer.parseInt(output3Array[i + 5]);
                break;
            }
            i += 5;
        }

        if (aCosts != -1) {

            for (int i = 0; i < counter2; i++) {
                if (output2Array[i].equals(this.getTitle())) {
                    if (output2Array[i + 1].equals("0")) {
                        String tempString = "Κωδικός πολυκατοικίας: " + output2Array[i] + "\t"
                                + "Όροφος: " + output2Array[i + 1] + "\t"
                                + "Κωδικός: " + output2Array[i + 2] + "\t"
                                + "Ονοματεπώνυμο: " + output2Array[i + 3] + "\t"
                                + "Τ.Μ.: " + output2Array[i + 4] + "\t"
                                + "Τηλέφωνο: " + output2Array[i + 5] + "\t"
                                + "Χιλιοστά: " + output2Array[i + 6] + "\r\n\r\n"
                                + "Μήνας και έτος: " + TextField1.getText() + "\r\n"
                                + "Ποσό κοινοχρήστων: " + (aCosts * Integer.parseInt(output2Array[i + 6]) / 1000) + "\r\n"
                                + "Ποσό θέρμανσης: " + (bCosts * Integer.parseInt(output2Array[i + 6]) / 1000) + "\r\n"
                                + "Ποσό συνδιοκτησίας: " + (cCosts * Integer.parseInt(output2Array[i + 6]) / 1000) + "\r\n"
                                + "Ποσό ανεκλυστήρα: " + "0";

                        try {
                            String fileName = this.getTitle() + output2Array[i + 2] + ".txt";
                            FileWriter f = new FileWriter(fileName);
                            BufferedWriter b = new BufferedWriter(f);
                            b.write(tempString);
                            b.close();
                        } catch (IOException e) {
                            System.out.println(e.getMessage());
                        }

                    } else {
                        String tempString = "Κωδικός πολυκατοικίας: " + output2Array[i] + "\t"
                                + "Όροφος: " + output2Array[i + 1] + "\t"
                                + "Κωδικός: " + output2Array[i + 2] + "\t"
                                + "Ονοματεπώνυμο: " + output2Array[i + 3] + "\t"
                                + "Τ.Μ.: " + output2Array[i + 4] + "\t"
                                + "Τηλέφωνο: " + output2Array[i + 5] + "\t"
                                + "Χιλιοστά: " + output2Array[i + 6] + "\r\n\r\n"
                                + "Μήνας και έτος: " + TextField1.getText() + "\r\n"
                                + "Ποσό κοινοχρήστων: " + (aCosts * Integer.parseInt(output2Array[i + 6]) / 1000) + "\r\n"
                                + "Ποσό θέρμανσης: " + (bCosts * Integer.parseInt(output2Array[i + 6]) / 1000) + "\r\n"
                                + "Ποσό συνδιοκτησίας: " + (cCosts * Integer.parseInt(output2Array[i + 6]) / 1000) + "\r\n"
                                + "Ποσό ανεκλυστήρα: " + (dCosts * Integer.parseInt(output2Array[i + 6]) / 1000);

                        try {
                            String fileName = this.getTitle() + output2Array[i + 2] + ".txt";
                            FileWriter f = new FileWriter(fileName);
                            BufferedWriter b = new BufferedWriter(f);
                            b.write(tempString);
                            b.close();
                        } catch (IOException e) {
                            System.out.println(e.getMessage());
                        }
                    }
                }
                i += 6;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Δεν είναι έτοιμα τα έξοδα για αυτόν τον μήνα και έτος!");
            return;
        }
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FourthInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FourthInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FourthInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FourthInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FourthInputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
